var transl8 = transl8 || {};
transl8['de'] = {
"backend_missing": "Die Verbindung zum Arachne-Server konnte nicht hergestellt werden.",
"components.message.contact": "Bitte kontaktieren Sie CONTACT, sollte der Fehler weiterhin auftreten.",
"contact_first_surname": "Vor- & Nachname",
"contact_success": "Nachricht versendet. Sie sollten in Kürze eine eMail von uns erhalten.",
"core_fields": "Kernfelder",
"create_period": "Neue Periode anlegen",
"default": "Ein unbekannter Fehler ist aufgetreten.",
"everything_fine": "Alles in bester Ordnung",
"example_queries": "Beispielabfragen",
"example_query_ancient_egypt": "kuratierte Sammlung: altes Ägypten",
"example_query_arachne": "Beispielsuche: Provenienz \"Arachne\"",
"example_query_augustan": "Beispielsuche \"augusteisch\"",
"example_query_bronze_age_europe": "kuratierte Sammlung: Bronzezeit in Europa",
"example_query_geological_time_scale": "kuratierte Sammlung: geologische Zeitskala",
"example_query_roman_chronology": "kuratierte Sammlung: römische Chronologie",
"footer_bugs_to": "Fehlermeldungen bitte an",
"footer_licensed_under": "Lizensiert unter",
"footer_privacy": "Datenschutz",
"form_reset": "Zurücksetzen",
"form_save": "Speichern",
"inactive_timeline": "Keine Zeitspanne definiert",
"navbar_leave_scope": "Suchbereich verlassen",
"navbar_old_searches": "Ältere Suchen",
"navbar_placeholder_search": "Neue Suche",
"navbar_sign_in": "Anmelden",
"navbar_sign_out": "Abmelden",
"navbar_sign_up": "Registrieren",
"navbar_this_scope": "Dieser Suchbereich",
"no_map_data": "Keine Ortsdaten vorhanden",
"period_definition": "Definition",
"period_description": "Beschreibung",
"period_names": "Namen",
"period_note": "Notiz",
"period_ongoing": "dauert noch an",
"period_prefName": "Name",
"period_provenance": "digitale Provenienz",
"period_region": "Region",
"period_tags": "Tags",
"period_temporalExtent": "Zeitliche Ausdehnung",
"period_type": "Epochentyp",
"period_types": "Epochentypen",
"pick_an_item": "Wählen Sie einen Eintrag",
"picker_no_result": "Keine Einträge gefunden",
"picker_perform_search": "Starten Sie eine Suchanfrage, um einen Eintrag auszuwählen",
"relation_contains": "Umfasst",
"relation_differsInDefinitionFrom": "Hat andere Definition als",
"relation_fallsWithin": "Fällt in",
"relation_fields": "Beziehungsfelder",
"relation_finishes": "Ist Ende von",
"relation_follows": "Folgt auf",
"relation_hasCoreArea": "Hat Kerngebiet",
"relation_hasPart": "Hat Unterteilungen",
"relation_hasSense": "Hat als eine Bedeutung",
"relation_hasTimespan": "Zeitliche Ausdehnung",
"relation_includes": "Schließt ein",
"relation_isEqualInTimeTo": "Gleichzeitig mit",
"relation_isFinishedBy": "Hat Ende",
"relation_isFollowedBy": "Wird gefolgt von",
"relation_isListedIn": "Wird aufgelistet in",
"relation_isMetInTimeBy": "Genau nach",
"relation_isNamedAfter": "Ist benannt nach",
"relation_isOverlappedInTimeBy": "Überschneidend nach",
"relation_isPartOf": "Ist Teil von",
"relation_isSenseOf": "Ist eine Bedeutung von",
"relation_isSimilarTo": "ist vergleichbar mit",
"relation_isStartedBy": "Hat Anfang",
"relation_lists": "Listet",
"relation_meetsInTimeWith": "Genau vor",
"relation_occursAfter": "Irgendwann nach",
"relation_occursBefore": "Irgendwann vor",
"relation_occursDuring": "Passiert während",
"relation_overlapsInTimeWith": "Überschneidend vor",
"relation_sameAs": "Entspricht",
"relation_spatiallyPartOfRegion": "Räumlich Teil von",
"relation_starts": "Ist Anfang von",
"results": "Ergebnisse",
"temporal_at_precision": "ungenau",
"temporal_begin": "Beginn",
"temporal_calendar": "Kalender:",
"temporal_description": "Beschreibung",
"temporal_end": "Ende",
"temporal_notAfter": "nicht nach",
"temporal_notBefore": "nicht vor",
"test": "von chronontology",
"type_allMeanings": "alle Bedeutungen",
"type_political": "politisch",
"ui_add_language": "Sprache hinzufügen",
"ui_add_name": "Namen hinzufügen",
"ui_add_tag": "Tag hinzufügen",
"ui_add_value": "Wert hinzufügen",
"ui_back": "Zurück",
"ui_created": "Erstellt",
"ui_derived_from": "Abgeleitet von",
"ui_derivedInfo": "Abgeleitete Informationen",
"ui_editTab": "Bearbeiten",
"ui_entries": "Einträge",
"ui_filter_exists": "Ist gesetzt",
"ui_filter_plural": "Filter",
"ui_general_relations": "Allgemeine Relationen",
"ui_geographic_relations": "Geographische Relationen",
"ui_infoTab": "Informationen",
"ui_list": "Liste",
"ui_login_failed": "Anmeldung fehlgeschlagen, bitte erneut versuchen!",
"ui_login_successfull": "Anmeldung erfolgreich. Nutzer",
"ui_login": "Anmeldung",
"ui_message": "Nachricht",
"ui_metadata": "Dokumentmetadaten",
"ui_modified": "Geändert",
"ui_next": "Weiter",
"ui_nomachine": "Ich bin keine Maschine",
"ui_original_text": "Text im Original",
"ui_page": "Seite",
"ui_password": "Passwort",
"ui_periodInfo": "Informationen zur Epoche",
"ui_placeholder_search": "Suche",
"ui_please_select": "Bitte auswählen",
"ui_previous": "Zurück",
"ui_relations": "Beziehungen",
"ui_search_view": "Suchergebnisdarstellung",
"ui_send": "Senden",
"ui_showall": "Alle anzeigen",
"ui_source_url": "Link",
"ui_source": "Quelle",
"ui_subject": "Betreff",
"ui_temporal_relations_according_to": "nach",
"ui_temporal_relations": "Temporale Relationen",
"ui_timeline_greater_than_max": "Das Suchergebnis ist zu groß um komplett auf der Zeitleiste dargestellt zu werden. Bitte nutzen Sie die Filter um die Anzahl der Treffer zu reduzieren.",
"ui_timeline": "Zeitstrahl",
"ui_total": "Insgesamt",
"ui_username": "Benutzername",
"value_provenance_aat": "Getty AAT",
"value_provenance_Arachne": "iDAI.objects Arachne",
"value_provenance_Chronontology": "chronOntology",
"value_provenance_Landesarchäologen": "Verband der Landesarchäologen",
"value_provenance_periodo": "PeriodO",
"value_provenance_SPP2143": "Entangled Africa",
"value_types_age": "Alter (Geologie)",
"value_types_archaeobotanical": "archäobotanisch",
"value_types_architecture": "Architektur",
"value_types_art": "Kunst",
"value_types_burial": "Begräbnis",
"value_types_ceramic": "Keramik (ceramic)",
"value_types_chronological_subdivision": "chronologische Unterteilung",
"value_types_collection": "Epochenliste",
"value_types_cultural": "kulturell",
"value_types_decorative_arts": "dekorative Kunst",
"value_types_eon": "Äon (Geologie)",
"value_types_epoch": "Epoche (Geologie)",
"value_types_era": "Ära (Geologie)",
"value_types_fine_arts": "bildende Kunst",
"value_types_geological": "geologisch",
"value_types_glass_vessels": "Glasgefäße",
"value_types_glass": "Glas",
"value_types_glyptic": "Glyptik",
"value_types_historical": "historisch",
"value_types_iron": "iron",
"value_types_iron_age": "iron age",
"value_types_lacquer": "Lack",
"value_types_lithic": "lithic",
"value_types_material_culture": "materielle Kultur",
"value_types_metal_bowls": "Metallschalen",
"value_types_metal_ware": "Metallwaren",
"value_types_not_specified": "kein Typ",
"value_types_painting": "Malerei",
"value_types_period": "Periode (Geologie)",
"value_types_photography": "Fotografie",
"value_types_political": "politisch",
"value_types_porcelain": "Porzellan",
"value_types_pottery": "Keramikstil",
"value_types_printmaking": "Druckgrafik",
"value_types_rock_art": "Felskunst",
"value_types_sculpture": "Bildhauerei",
"value_types_stone_tools": "Steinwerkzeug",
"value_types_supereon": "Super-Äon (Geologie)",
"value_types_textile": "Textilien",
"value_types_wall_painting": "Wandmalerei",
"welcome": "Willkommen"
};
