var transl8 = transl8 || {};
transl8['en'] = {
"backend_missing": "Connection to the arachne backend cannot not be established.",
"components.message.contact": "Please contact CONTACT if the errors persist.",
"contact_first_surname": "First name & surname",
"contact_success": "Message has been sent. We will contact you by email as soon as possible.",
"core_fields": "Core fields",
"create_period": "Create period",
"default": "An unknown error has occured.",
"everything_fine": "Everything fine",
"example_queries": "Example queries",
"example_query_ancient_egypt": "curated list: Ancient Egypt",
"example_query_arachne": "sample search: provenance \"Arachne\"",
"example_query_augustan": "sample search \"Augustan\"",
"example_query_bronze_age_europe": "curated list: Bronze Age in Europe",
"example_query_geological_time_scale": "curated list: geological time scale",
"example_query_roman_chronology": "curated list: Roman chronology",
"footer_bugs_to": "Report bugs to",
"footer_licensed_under": "Licensed under",
"footer_privacy": "Privacy",
"form_reset": "Reset",
"form_save": "Save",
"inactive_timeline": "No timespan defined",
"navbar_leave_scope": "Leave Search Scope",
"navbar_old_searches": "Recently searched for",
"navbar_placeholder_search": "Search for",
"navbar_sign_in": "Sign In",
"navbar_sign_out": "Sign Out",
"navbar_sign_up": "Sign Up",
"navbar_this_scope": "This Scope",
"no_map_data": "No map data available",
"period_definition": "Definition",
"period_description": "Description",
"period_names": "Names",
"period_note": "Note",
"period_ongoing": "still ongoing",
"period_prefName": "Name",
"period_provenance": "Digital provenance",
"period_region": "Region",
"period_tags": "Tags",
"period_temporalExtent": "Temporal extent",
"period_type": "Period type",
"period_types": "Period types",
"pick_an_item": "Pick an item",
"picker_no_result": "No items found",
"picker_perform_search": "Perform a search to pick an item",
"relation_contains": "Contains",
"relation_differsInDefinitionFrom": "Differs in definition from",
"relation_fallsWithin": "Falls within",
"relation_fields": "Relation fields",
"relation_finishes": "Finishes",
"relation_follows": "Follows",
"relation_hasCoreArea": "Has core area",
"relation_hasPart": "Has parts",
"relation_hasSense": "Has senses",
"relation_hasTimespan": "Temporal extent",
"relation_includes": "Includes",
"relation_isEqualInTimeTo": "Is equal in time to",
"relation_isFinishedBy": "Is Finished by",
"relation_isFollowedBy": "Is followed by",
"relation_isListedIn": "Is listed in",
"relation_isMetInTimeBy": "Is met in time by",
"relation_isNamedAfter": "Is named after",
"relation_isOverlappedInTimeBy": "Is overlapped in time by",
"relation_isPartOf": "Is part of",
"relation_isSenseOf": "Is a sense of",
"relation_isSimilarTo": "Is similar to",
"relation_isStartedBy": "Is started by",
"relation_lists": "Lists",
"relation_meetsInTimeWith": "Meets in time with",
"relation_occursAfter": "Occurs after",
"relation_occursBefore": "Occurs before",
"relation_occursDuring": "Occurs during",
"relation_overlapsInTimeWith": "Overlaps in time with",
"relation_sameAs": "Same as",
"relation_spatiallyPartOfRegion": "Spatially part of region",
"relation_starts": "Starts",
"results": "Results",
"temporal_at_precision": "imprecise",
"temporal_begin": "Begin",
"temporal_calendar": "Calendar:",
"temporal_description": "Description",
"temporal_end": "End",
"temporal_notAfter": "not after",
"temporal_notBefore": "not before",
"test": "from chronontology",
"type_allMeanings": "all meanings",
"type_political": "Political",
"ui_add_language": "Add language",
"ui_add_name": "Add name",
"ui_add_tag": "Add tag",
"ui_add_value": "Add value",
"ui_back": "Back",
"ui_created": "Created",
"ui_derived_from": "Derived from",
"ui_derivedInfo": "Derived information",
"ui_editTab": "Edit",
"ui_entries": "Entries",
"ui_filter_exists": "Is set",
"ui_filter_plural": "Filters",
"ui_general_relations": "General relations",
"ui_geographic_relations": "Geographic relations",
"ui_infoTab": "Information",
"ui_list": "List",
"ui_login_failed": "Login failed. Please try again!",
"ui_login_successfull": "Login successful. User",
"ui_login": "login",
"ui_message": "Message",
"ui_metadata": "Document metadata",
"ui_modified": "Modified",
"ui_next": "Next",
"ui_nomachine": "I'm not a machine",
"ui_original_text": "Original text",
"ui_page": "Page",
"ui_password": "Password",
"ui_periodInfo": "About the period",
"ui_placeholder_search": "Search",
"ui_please_select": "Please select",
"ui_previous": "Previous",
"ui_relations": "Relations",
"ui_search_view": "View result as",
"ui_send": "Send",
"ui_showall": "Show all",
"ui_source_url": "Link",
"ui_source": "Source",
"ui_subject": "Subject",
"ui_temporal_relations_according_to": "according to",
"ui_temporal_relations": "Temporal relations",
"ui_timeline_greater_than_max": "The search result is too large to be rendered on the timeline completely. Use the filters to narrow down the result in order for every item matching your query to be displayed.",
"ui_timeline": "Timeline",
"ui_total": "Total",
"ui_username": "User Name",
"value_provenance_aat": "Getty AAT",
"value_provenance_Arachne": "iDAI.objects Arachne",
"value_provenance_Chronontology": "chronOntology",
"value_provenance_Landesarchäologen": "Verband der Landesarchäologen",
"value_provenance_periodo": "PeriodO",
"value_provenance_SPP2143": "SPP2143",
"value_types_age": "Age (geology)",
"value_types_archaeobotanical": "archaeobotanical",
"value_types_architecture": "architecture",
"value_types_art": "art",
"value_types_burial": "burial",
"value_types_ceramic": "ceramic",
"value_types_chronological_subdivision": "chronological subdivision",
"value_types_collection": "period list",
"value_types_cultural": "cultural",
"value_types_decorative_arts": "decorative arts",
"value_types_eon": "Eon (geology)",
"value_types_epoch": "Epoch (geology)",
"value_types_era": "Era (geology)",
"value_types_fine_arts": "fine arts",
"value_types_geological": "geological",
"value_types_glass_vessels": "glass vessels",
"value_types_glass": "glass",
"value_types_glyptic": "glyptic",
"value_types_historical": "historical",
"value_types_iron": "iron",
"value_types_iron_age": "iron age",
"value_types_lacquer": "lacquer",
"value_types_lithic": "lithic",
"value_types_material_culture": "material culture",
"value_types_metal_bowls": "metal bowls",
"value_types_metal_ware": "metal ware",
"value_types_not_specified": "not specified",
"value_types_painting": "painting",
"value_types_period": "Period (geology)",
"value_types_photography": "photography",
"value_types_political": "political",
"value_types_porcelain": "porcelain",
"value_types_pottery": "pottery style",
"value_types_printmaking": "printmaking",
"value_types_rock_art": "rock art",
"value_types_sculpture": "sculpture",
"value_types_stone_tools": "stone tools",
"value_types_supereon": "Supereon (geology)",
"value_types_textile": "textile",
"value_types_wall_painting": "wall painting",
"welcome": "Welcome"
};
