var transl8 = transl8 || {};
transl8['en'] = {
"period_prefName": "Name",
"period_type": "Period type",
"period_provenance": "Digital provenance",
"relation_isSenseOf": "Is a sense of",
"relation_hasSense": "Has senses",
"relation_isPartOf": "Is part of",
"relation_hasPart": "Has parts",
"relation_isListedIn": "Is listed in",
"relation_lists": "Lists",
"relation_follows": "Follows",
"relation_isFollowedBy": "Is followed by",
"relation_sameAs": "Same as",
"relation_isNamedAfter": "Is named after",
"relation_hasCoreArea": "Has core area",
"relation_spatiallyPartOfRegion": "Spatially part of region",
"ui_infoTab": "Information",
"ui_editTab": "Edit",
"ui_periodInfo": "About the period",
"period_description": "Description",
"period_definition": "Definition",
"period_temporalExtent": "Temporal extent",
"ui_relations": "Relations",
"ui_metadata": "Document metadata",
"ui_created": "Created",
"ui_modified": "Modified",
"type_political": "Political",
"type_allMeanings": "all meanings",
"period_names": "Names",
"period_tags": "Tags",
"period_note": "Note",
"period_ongoing": "still ongoing",
"temporal_begin": "Begin",
"temporal_end": "End",
"temporal_notBefore": "not before",
"temporal_notAfter": "not after",
"temporal_calendar": "Calendar:",
"ui_source": "Source",
"test": "from chronontology",
"relation_isSimilarTo": "Is similar to",
"relation_includes": "Includes",
"relation_occursDuring": "Occurs during",
"relation_meetsInTimeWith": "Meets in time with",
"relation_isMetInTimeBy": "Is met in time by",
"relation_occursBefore": "Occurs before",
"relation_occursAfter": "Occurs after",
"relation_isEqualInTimeTo": "Is equal in time to",
"relation_starts": "Starts",
"relation_isStartedBy": "Is started by",
"relation_finishes": "Finishes",
"relation_isFinishedBy": "Is Finished by",
"relation_overlapsInTimeWith": "Overlaps in time with",
"relation_isOverlappedInTimeBy": "Is overlapped in time by",
"ui_derivedInfo": "Derived information",
"period_region": "Region",
"relation_fallsWithin": "Falls within",
"relation_contains": "Contains",
"temporal_at_precision": "imprecise",
"ui_source_url": "Link",
"create_period": "Create period",
"core_fields": "Core fields",
"relation_fields": "Relation fields",
"no_map_data": "No map data available",
"inactive_timeline": "No timespan defined",
"ui_general_relations": "General relations",
"ui_temporal_relations": "Temporal relations",
"ui_temporal_relations_according_to": "according to",
"ui_geographic_relations": "Geographic relations",
"relation_hasTimespan": "Temporal extent",
"period_types": "Period types",
"ui_filter_exists": "Is set",
"welcome": "Welcome",
"example_queries": "Example queries",
"example_query_augustan": "sample search \"Augustan\"",
"example_query_arachne": "sample search: provenance \"Arachne\"",
"ui_timeline": "Timeline",
"ui_list": "List",
"ui_search_view": "View result as",
"ui_original_text": "Original text",
"ui_derived_from": "Derived from",
"ui_timeline_greater_than_max": "The search result is too large to be rendered on the timeline completely. Use the filters to narrow down the result in order for every item matching your query to be displayed.",
"value_types_collection": "period list",
"value_types_painting": "painting",
"value_types_cultural": "cultural",
"value_types_architecture": "architecture",
"value_types_not_specified": "not specified",
"value_types_age": "Age (geology)",
"value_types_political": "political",
"value_types_pottery": "pottery style",
"value_types_geological": "geological",
"value_types_material_culture": "material culture",
"value_provenance_aat": "Getty AAT",
"value_provenance_Chronontology": "chronOntology",
"value_provenance_Arachne": "iDAI.objects Arachne",
"value_types_textile": "textile",
"value_types_ceramic": "ceramic",
"value_types_sculpture": "sculpture",
"value_types_printmaking": "printmaking",
"value_provenance_Landesarchäologen": "Verband der Landesarchäologen",
"example_query_ancient_egypt": "curated list: Ancient Egypt",
"example_query_bronze_age_europe": "curated list: Bronze Age in Europe",
"example_query_geological_time_scale": "curated list: geological time scale",
"example_query_roman_chronology": "curated list: Roman chronology",
"value_types_epoch": "Epoch (geology)",
"value_types_period": "Period (geology)",
"value_types_eon": "Eon (geology)",
"value_types_era": "Era (geology)",
"value_types_supereon": "Supereon (geology)",
"value_types_historical": "historical",
"value_types_glass_vessels": "glass vessels",
"value_types_chronological_subdivision": "chronological subdivision",
"value_provenance_periodo": "PeriodO",
"relation_differsInDefinitionFrom": "Differs in definition from",
"value_types_stone_tools": "stone tools",
"value_types_rock_art": "rock art",
"value_types_fine_arts": "fine arts",
"value_types_decorative_arts": "decorative arts",
"value_types_porcelain": "porcelain",
"value_types_lacquer": "lacquer",
"value_types_wall_painting": "wall painting",
"value_types_metal_bowls": "metal bowls",
"value_types_glyptic": "glyptic",
"value_types_photography": "photography",
"value_types_glass": "glass",
"value_types_metal_ware": "metal ware",
"value_types_art": "art",
"ui_please_select": "Please select",
"ui_username": "User Name",
"ui_password": "Password",
"ui_entries": "Entries",
"ui_total": "Total",
"footer_privacy": "Privacy",
"backend_missing": "Connection to the arachne backend cannot not be established.",
"default": "An unknown error has occured.",
"ui_filter_plural": "Filters",
"pick_an_item": "Pick an item",
"form_save": "Save",
"form_reset": "Reset",
"picker_perform_search": "Perform a search to pick an item",
"picker_no_result": "No items found",
"results": "Results",
"everything_fine": "Everything fine",
"components.message.contact": "Please contact CONTACT if the errors persist.",
"ui_login": "login",
"ui_login_failed": "Login failed. Please try again!",
"ui_page": "Page",
"ui_previous": "Previous",
"ui_next": "Next",
"contact_success": "Message has been sent. We will contact you by email as soon as possible.",
"navbar_sign_up": "Sign Up",
"footer_licensed_under": "Licensed under",
"footer_bugs_to": "Report bugs to",
"contact_first_surname": "First name & surname",
"ui_subject": "Subject",
"ui_message": "Message",
"ui_nomachine": "I'm not a machine",
"navbar_placeholder_search": "Search for",
"ui_send": "Send",
"ui_placeholder_search": "Search",
"ui_showall": "Show all",
"navbar_sign_in": "Sign In",
"navbar_sign_out": "Sign Out",
"navbar_old_searches": "Recently searched for",
"ui_back": "Back",
"ui_add_value": "Add value",
"ui_add_tag": "Add tag",
"ui_add_name": "Add name",
"ui_add_language": "Add language",
"navbar_this_scope": "This Scope",
"navbar_leave_scope": "Leave Search Scope"
};
